[[tasks]]
name = "Example News Site"
mode = "trafilatura"
start_urls = [
    "http://www.example.com/news/article1",
    "http://www.example.com/news/article2",
]
javascript = false
crawl = true
handle_pdfs = false

[tasks.crawl_rules]
allow = ["/news/"]
deny = ["/archive/", "/login/"]

[[tasks]]
name = "Another Example Site"
mode = "trafilatura"
start_urls = [
    "http://blog.example.org/",
]
javascript = true
crawl = false
